"""HTML5 constants — matching html5lib exactly."""

from __future__ import annotations

import string


EOF = None

tokenTypes = {
    'Doctype': 0,
    'Characters': 1,
    'SpaceCharacters': 2,
    'StartTag': 3,
    'EndTag': 4,
    'EmptyTag': 5,
    'Comment': 6,
    'ParseError': 7,
}

tagTokenTypes = frozenset({3, 4, 5})

namespaces = {
    'html': 'http://www.w3.org/1999/xhtml',
    'mathml': 'http://www.w3.org/1998/Math/MathML',
    'svg': 'http://www.w3.org/2000/svg',
    'xlink': 'http://www.w3.org/1999/xlink',
    'xml': 'http://www.w3.org/XML/1998/namespace',
    'xmlns': 'http://www.w3.org/2000/xmlns/',
}

prefixes = {v: k for k, v in namespaces.items()}
prefixes["http://www.w3.org/1998/Math/MathML"] = "math"

asciiLetters = frozenset(string.ascii_letters)
asciiUppercase = frozenset(string.ascii_uppercase)
asciiLowercase = frozenset(string.ascii_lowercase)
digits = frozenset(string.digits)
hexDigits = frozenset(string.hexdigits)

asciiUpper2Lower = {
    65: 97,
    66: 98,
    67: 99,
    68: 100,
    69: 101,
    70: 102,
    71: 103,
    72: 104,
    73: 105,
    74: 106,
    75: 107,
    76: 108,
    77: 109,
    78: 110,
    79: 111,
    80: 112,
    81: 113,
    82: 114,
    83: 115,
    84: 116,
    85: 117,
    86: 118,
    87: 119,
    88: 120,
    89: 121,
    90: 122,
}

spaceCharacters = frozenset("\t\n\u000C \r")

voidElements = frozenset([
    'area',
    'base',
    'br',
    'col',
    'command',
    'embed',
    'event-source',
    'hr',
    'img',
    'input',
    'link',
    'meta',
    'param',
    'source',
    'track',
])

cdataElements = frozenset([
    'textarea',
    'title',
])

rcdataElements = frozenset([
    'iframe',
    'noembed',
    'noframes',
    'noscript',
    'script',
    'style',
    'xmp',
])

headingElements = (
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
)

tableInsertModeElements = frozenset([
    'table',
    'tbody',
    'tfoot',
    'thead',
    'tr',
])

scopingElements = frozenset([
    (namespaces['mathml'], 'annotation-xml'),
    (namespaces['mathml'], 'mi'),
    (namespaces['mathml'], 'mn'),
    (namespaces['mathml'], 'mo'),
    (namespaces['mathml'], 'ms'),
    (namespaces['mathml'], 'mtext'),
    (namespaces['html'], 'applet'),
    (namespaces['html'], 'caption'),
    (namespaces['html'], 'html'),
    (namespaces['html'], 'marquee'),
    (namespaces['html'], 'object'),
    (namespaces['html'], 'table'),
    (namespaces['html'], 'td'),
    (namespaces['html'], 'th'),
    (namespaces['svg'], 'desc'),
    (namespaces['svg'], 'foreignObject'),
    (namespaces['svg'], 'title'),
])

formattingElements = frozenset([
    (namespaces['html'], 'a'),
    (namespaces['html'], 'b'),
    (namespaces['html'], 'big'),
    (namespaces['html'], 'code'),
    (namespaces['html'], 'em'),
    (namespaces['html'], 'font'),
    (namespaces['html'], 'i'),
    (namespaces['html'], 'nobr'),
    (namespaces['html'], 's'),
    (namespaces['html'], 'small'),
    (namespaces['html'], 'strike'),
    (namespaces['html'], 'strong'),
    (namespaces['html'], 'tt'),
    (namespaces['html'], 'u'),
])

specialElements = frozenset([
    (namespaces['html'], 'address'),
    (namespaces['html'], 'applet'),
    (namespaces['html'], 'area'),
    (namespaces['html'], 'article'),
    (namespaces['html'], 'aside'),
    (namespaces['html'], 'base'),
    (namespaces['html'], 'basefont'),
    (namespaces['html'], 'bgsound'),
    (namespaces['html'], 'blockquote'),
    (namespaces['html'], 'body'),
    (namespaces['html'], 'br'),
    (namespaces['html'], 'button'),
    (namespaces['html'], 'caption'),
    (namespaces['html'], 'center'),
    (namespaces['html'], 'col'),
    (namespaces['html'], 'colgroup'),
    (namespaces['html'], 'command'),
    (namespaces['html'], 'dd'),
    (namespaces['html'], 'details'),
    (namespaces['html'], 'dir'),
    (namespaces['html'], 'div'),
    (namespaces['html'], 'dl'),
    (namespaces['html'], 'dt'),
    (namespaces['html'], 'embed'),
    (namespaces['html'], 'fieldset'),
    (namespaces['html'], 'figure'),
    (namespaces['html'], 'footer'),
    (namespaces['html'], 'form'),
    (namespaces['html'], 'frame'),
    (namespaces['html'], 'frameset'),
    (namespaces['html'], 'h1'),
    (namespaces['html'], 'h2'),
    (namespaces['html'], 'h3'),
    (namespaces['html'], 'h4'),
    (namespaces['html'], 'h5'),
    (namespaces['html'], 'h6'),
    (namespaces['html'], 'head'),
    (namespaces['html'], 'header'),
    (namespaces['html'], 'hr'),
    (namespaces['html'], 'html'),
    (namespaces['html'], 'iframe'),
    (namespaces['html'], 'image'),
    (namespaces['html'], 'img'),
    (namespaces['html'], 'input'),
    (namespaces['html'], 'isindex'),
    (namespaces['html'], 'li'),
    (namespaces['html'], 'link'),
    (namespaces['html'], 'listing'),
    (namespaces['html'], 'marquee'),
    (namespaces['html'], 'menu'),
    (namespaces['html'], 'meta'),
    (namespaces['html'], 'nav'),
    (namespaces['html'], 'noembed'),
    (namespaces['html'], 'noframes'),
    (namespaces['html'], 'noscript'),
    (namespaces['html'], 'object'),
    (namespaces['html'], 'ol'),
    (namespaces['html'], 'p'),
    (namespaces['html'], 'param'),
    (namespaces['html'], 'plaintext'),
    (namespaces['html'], 'pre'),
    (namespaces['html'], 'script'),
    (namespaces['html'], 'section'),
    (namespaces['html'], 'select'),
    (namespaces['html'], 'style'),
    (namespaces['html'], 'table'),
    (namespaces['html'], 'tbody'),
    (namespaces['html'], 'td'),
    (namespaces['html'], 'textarea'),
    (namespaces['html'], 'tfoot'),
    (namespaces['html'], 'th'),
    (namespaces['html'], 'thead'),
    (namespaces['html'], 'title'),
    (namespaces['html'], 'tr'),
    (namespaces['html'], 'ul'),
    (namespaces['html'], 'wbr'),
    (namespaces['html'], 'xmp'),
    (namespaces['svg'], 'foreignObject'),
])

htmlIntegrationPointElements = frozenset([
    (namespaces['mathml'], 'annotation-xml'),
    (namespaces['svg'], 'desc'),
    (namespaces['svg'], 'foreignObject'),
    (namespaces['svg'], 'title'),
])

mathmlTextIntegrationPointElements = frozenset([
    (namespaces['mathml'], 'mi'),
    (namespaces['mathml'], 'mn'),
    (namespaces['mathml'], 'mo'),
    (namespaces['mathml'], 'ms'),
    (namespaces['mathml'], 'mtext'),
])

booleanAttributes = {
    '': frozenset(['irrelevant', 'itemscope']),
    'audio': frozenset(['autoplay', 'controls']),
    'button': frozenset(['autofocus', 'disabled']),
    'command': frozenset(['checked', 'default', 'disabled', 'hidden']),
    'datagrid': frozenset(['disabled', 'multiple']),
    'details': frozenset(['open']),
    'fieldset': frozenset(['disabled', 'readonly']),
    'hr': frozenset(['noshade']),
    'iframe': frozenset(['seamless']),
    'img': frozenset(['ismap']),
    'input': frozenset(['autofocus', 'checked', 'disabled', 'ismap', 'readonly', 'required']),
    'menu': frozenset(['autosubmit']),
    'optgroup': frozenset(['disabled', 'readonly']),
    'option': frozenset(['disabled', 'readonly', 'selected']),
    'output': frozenset(['disabled', 'readonly']),
    'script': frozenset(['async', 'defer']),
    'select': frozenset(['autofocus', 'disabled', 'multiple', 'readonly']),
    'style': frozenset(['scoped']),
    'video': frozenset(['autoplay', 'controls']),
}

adjustSVGAttributes = {
    'attributename': 'attributeName',
    'attributetype': 'attributeType',
    'basefrequency': 'baseFrequency',
    'baseprofile': 'baseProfile',
    'calcmode': 'calcMode',
    'clippathunits': 'clipPathUnits',
    'contentscripttype': 'contentScriptType',
    'contentstyletype': 'contentStyleType',
    'diffuseconstant': 'diffuseConstant',
    'edgemode': 'edgeMode',
    'externalresourcesrequired': 'externalResourcesRequired',
    'filterres': 'filterRes',
    'filterunits': 'filterUnits',
    'glyphref': 'glyphRef',
    'gradienttransform': 'gradientTransform',
    'gradientunits': 'gradientUnits',
    'kernelmatrix': 'kernelMatrix',
    'kernelunitlength': 'kernelUnitLength',
    'keypoints': 'keyPoints',
    'keysplines': 'keySplines',
    'keytimes': 'keyTimes',
    'lengthadjust': 'lengthAdjust',
    'limitingconeangle': 'limitingConeAngle',
    'markerheight': 'markerHeight',
    'markerunits': 'markerUnits',
    'markerwidth': 'markerWidth',
    'maskcontentunits': 'maskContentUnits',
    'maskunits': 'maskUnits',
    'numoctaves': 'numOctaves',
    'pathlength': 'pathLength',
    'patterncontentunits': 'patternContentUnits',
    'patterntransform': 'patternTransform',
    'patternunits': 'patternUnits',
    'pointsatx': 'pointsAtX',
    'pointsaty': 'pointsAtY',
    'pointsatz': 'pointsAtZ',
    'preservealpha': 'preserveAlpha',
    'preserveaspectratio': 'preserveAspectRatio',
    'primitiveunits': 'primitiveUnits',
    'refx': 'refX',
    'refy': 'refY',
    'repeatcount': 'repeatCount',
    'repeatdur': 'repeatDur',
    'requiredextensions': 'requiredExtensions',
    'requiredfeatures': 'requiredFeatures',
    'specularconstant': 'specularConstant',
    'specularexponent': 'specularExponent',
    'spreadmethod': 'spreadMethod',
    'startoffset': 'startOffset',
    'stddeviation': 'stdDeviation',
    'stitchtiles': 'stitchTiles',
    'surfacescale': 'surfaceScale',
    'systemlanguage': 'systemLanguage',
    'tablevalues': 'tableValues',
    'targetx': 'targetX',
    'targety': 'targetY',
    'textlength': 'textLength',
    'viewbox': 'viewBox',
    'viewtarget': 'viewTarget',
    'xchannelselector': 'xChannelSelector',
    'ychannelselector': 'yChannelSelector',
    'zoomandpan': 'zoomAndPan',
}

adjustMathMLAttributes = {
    'definitionurl': 'definitionURL',
}

adjustForeignAttributes = {
    'xlink:actuate': ('xlink', 'actuate', 'http://www.w3.org/1999/xlink'),
    'xlink:arcrole': ('xlink', 'arcrole', 'http://www.w3.org/1999/xlink'),
    'xlink:href': ('xlink', 'href', 'http://www.w3.org/1999/xlink'),
    'xlink:role': ('xlink', 'role', 'http://www.w3.org/1999/xlink'),
    'xlink:show': ('xlink', 'show', 'http://www.w3.org/1999/xlink'),
    'xlink:title': ('xlink', 'title', 'http://www.w3.org/1999/xlink'),
    'xlink:type': ('xlink', 'type', 'http://www.w3.org/1999/xlink'),
    'xml:base': ('xml', 'base', 'http://www.w3.org/XML/1998/namespace'),
    'xml:lang': ('xml', 'lang', 'http://www.w3.org/XML/1998/namespace'),
    'xml:space': ('xml', 'space', 'http://www.w3.org/XML/1998/namespace'),
    'xmlns': (None, 'xmlns', 'http://www.w3.org/2000/xmlns/'),
    'xmlns:xlink': ('xmlns', 'xlink', 'http://www.w3.org/2000/xmlns/'),
}

unadjustForeignAttributes = {
    (prefix, local): attr
    for attr, (prefix, local, ns) in adjustForeignAttributes.items()
}

replacementCharacters = {
    0: '�',
    13: '\r',
    128: '€',
    129: '\x81',
    130: '‚',
    131: 'ƒ',
    132: '„',
    133: '…',
    134: '†',
    135: '‡',
    136: 'ˆ',
    137: '‰',
    138: 'Š',
    139: '‹',
    140: 'Œ',
    141: '\x8d',
    142: 'Ž',
    143: '\x8f',
    144: '\x90',
    145: '‘',
    146: '’',
    147: '“',
    148: '”',
    149: '•',
    150: '–',
    151: '—',
    152: '˜',
    153: '™',
    154: 'š',
    155: '›',
    156: 'œ',
    157: '\x9d',
    158: 'ž',
    159: 'Ÿ',
}

entitiesWindows1252 = (8364, 65533, 8218, 402, 8222, 8230, 8224, 8225, 710, 8240, 352, 8249, 338, 65533, 381, 65533, 65533, 8216, 8217, 8220, 8221, 8226, 8211, 8212, 732, 8482, 353, 8250, 339, 65533, 382, 376)

xmlEntities = frozenset([
    'amp;',
    'apos;',
    'gt;',
    'lt;',
    'quot;',
])


class DataLossWarning(UserWarning):
    """Warning issued when tree building may lose information."""
    pass

# ---------------------------------------------------------------------------
# Named character entities (2231 entries)
# ---------------------------------------------------------------------------

entities = {
    'AElig': 'Æ',
    'AElig;': 'Æ',
    'AMP': '&',
    'AMP;': '&',
    'Aacute': 'Á',
    'Aacute;': 'Á',
    'Abreve;': 'Ă',
    'Acirc': 'Â',
    'Acirc;': 'Â',
    'Acy;': 'А',
    'Afr;': '𝔄',
    'Agrave': 'À',
    'Agrave;': 'À',
    'Alpha;': 'Α',
    'Amacr;': 'Ā',
    'And;': '⩓',
    'Aogon;': 'Ą',
    'Aopf;': '𝔸',
    'ApplyFunction;': '\u2061',
    'Aring': 'Å',
    'Aring;': 'Å',
    'Ascr;': '𝒜',
    'Assign;': '≔',
    'Atilde': 'Ã',
    'Atilde;': 'Ã',
    'Auml': 'Ä',
    'Auml;': 'Ä',
    'Backslash;': '∖',
    'Barv;': '⫧',
    'Barwed;': '⌆',
    'Bcy;': 'Б',
    'Because;': '∵',
    'Bernoullis;': 'ℬ',
    'Beta;': 'Β',
    'Bfr;': '𝔅',
    'Bopf;': '𝔹',
    'Breve;': '˘',
    'Bscr;': 'ℬ',
    'Bumpeq;': '≎',
    'CHcy;': 'Ч',
    'COPY': '©',
    'COPY;': '©',
    'Cacute;': 'Ć',
    'Cap;': '⋒',
    'CapitalDifferentialD;': 'ⅅ',
    'Cayleys;': 'ℭ',
    'Ccaron;': 'Č',
    'Ccedil': 'Ç',
    'Ccedil;': 'Ç',
    'Ccirc;': 'Ĉ',
    'Cconint;': '∰',
    'Cdot;': 'Ċ',
    'Cedilla;': '¸',
    'CenterDot;': '·',
    'Cfr;': 'ℭ',
    'Chi;': 'Χ',
    'CircleDot;': '⊙',
    'CircleMinus;': '⊖',
    'CirclePlus;': '⊕',
    'CircleTimes;': '⊗',
    'ClockwiseContourIntegral;': '∲',
    'CloseCurlyDoubleQuote;': '”',
    'CloseCurlyQuote;': '’',
    'Colon;': '∷',
    'Colone;': '⩴',
    'Congruent;': '≡',
    'Conint;': '∯',
    'ContourIntegral;': '∮',
    'Copf;': 'ℂ',
    'Coproduct;': '∐',
    'CounterClockwiseContourIntegral;': '∳',
    'Cross;': '⨯',
    'Cscr;': '𝒞',
    'Cup;': '⋓',
    'CupCap;': '≍',
    'DD;': 'ⅅ',
    'DDotrahd;': '⤑',
    'DJcy;': 'Ђ',
    'DScy;': 'Ѕ',
    'DZcy;': 'Џ',
    'Dagger;': '‡',
    'Darr;': '↡',
    'Dashv;': '⫤',
    'Dcaron;': 'Ď',
    'Dcy;': 'Д',
    'Del;': '∇',
    'Delta;': 'Δ',
    'Dfr;': '𝔇',
    'DiacriticalAcute;': '´',
    'DiacriticalDot;': '˙',
    'DiacriticalDoubleAcute;': '˝',
    'DiacriticalGrave;': '`',
    'DiacriticalTilde;': '˜',
    'Diamond;': '⋄',
    'DifferentialD;': 'ⅆ',
    'Dopf;': '𝔻',
    'Dot;': '¨',
    'DotDot;': '⃜',
    'DotEqual;': '≐',
    'DoubleContourIntegral;': '∯',
    'DoubleDot;': '¨',
    'DoubleDownArrow;': '⇓',
    'DoubleLeftArrow;': '⇐',
    'DoubleLeftRightArrow;': '⇔',
    'DoubleLeftTee;': '⫤',
    'DoubleLongLeftArrow;': '⟸',
    'DoubleLongLeftRightArrow;': '⟺',
    'DoubleLongRightArrow;': '⟹',
    'DoubleRightArrow;': '⇒',
    'DoubleRightTee;': '⊨',
    'DoubleUpArrow;': '⇑',
    'DoubleUpDownArrow;': '⇕',
    'DoubleVerticalBar;': '∥',
    'DownArrow;': '↓',
    'DownArrowBar;': '⤓',
    'DownArrowUpArrow;': '⇵',
    'DownBreve;': '̑',
    'DownLeftRightVector;': '⥐',
    'DownLeftTeeVector;': '⥞',
    'DownLeftVector;': '↽',
    'DownLeftVectorBar;': '⥖',
    'DownRightTeeVector;': '⥟',
    'DownRightVector;': '⇁',
    'DownRightVectorBar;': '⥗',
    'DownTee;': '⊤',
    'DownTeeArrow;': '↧',
    'Downarrow;': '⇓',
    'Dscr;': '𝒟',
    'Dstrok;': 'Đ',
    'ENG;': 'Ŋ',
    'ETH': 'Ð',
    'ETH;': 'Ð',
    'Eacute': 'É',
    'Eacute;': 'É',
    'Ecaron;': 'Ě',
    'Ecirc': 'Ê',
    'Ecirc;': 'Ê',
    'Ecy;': 'Э',
    'Edot;': 'Ė',
    'Efr;': '𝔈',
    'Egrave': 'È',
    'Egrave;': 'È',
    'Element;': '∈',
    'Emacr;': 'Ē',
    'EmptySmallSquare;': '◻',
    'EmptyVerySmallSquare;': '▫',
    'Eogon;': 'Ę',
    'Eopf;': '𝔼',
    'Epsilon;': 'Ε',
    'Equal;': '⩵',
    'EqualTilde;': '≂',
    'Equilibrium;': '⇌',
    'Escr;': 'ℰ',
    'Esim;': '⩳',
    'Eta;': 'Η',
    'Euml': 'Ë',
    'Euml;': 'Ë',
    'Exists;': '∃',
    'ExponentialE;': 'ⅇ',
    'Fcy;': 'Ф',
    'Ffr;': '𝔉',
    'FilledSmallSquare;': '◼',
    'FilledVerySmallSquare;': '▪',
    'Fopf;': '𝔽',
    'ForAll;': '∀',
    'Fouriertrf;': 'ℱ',
    'Fscr;': 'ℱ',
    'GJcy;': 'Ѓ',
    'GT': '>',
    'GT;': '>',
    'Gamma;': 'Γ',
    'Gammad;': 'Ϝ',
    'Gbreve;': 'Ğ',
    'Gcedil;': 'Ģ',
    'Gcirc;': 'Ĝ',
    'Gcy;': 'Г',
    'Gdot;': 'Ġ',
    'Gfr;': '𝔊',
    'Gg;': '⋙',
    'Gopf;': '𝔾',
    'GreaterEqual;': '≥',
    'GreaterEqualLess;': '⋛',
    'GreaterFullEqual;': '≧',
    'GreaterGreater;': '⪢',
    'GreaterLess;': '≷',
    'GreaterSlantEqual;': '⩾',
    'GreaterTilde;': '≳',
    'Gscr;': '𝒢',
    'Gt;': '≫',
    'HARDcy;': 'Ъ',
    'Hacek;': 'ˇ',
    'Hat;': '^',
    'Hcirc;': 'Ĥ',
    'Hfr;': 'ℌ',
    'HilbertSpace;': 'ℋ',
    'Hopf;': 'ℍ',
    'HorizontalLine;': '─',
    'Hscr;': 'ℋ',
    'Hstrok;': 'Ħ',
    'HumpDownHump;': '≎',
    'HumpEqual;': '≏',
    'IEcy;': 'Е',
    'IJlig;': 'Ĳ',
    'IOcy;': 'Ё',
    'Iacute': 'Í',
    'Iacute;': 'Í',
    'Icirc': 'Î',
    'Icirc;': 'Î',
    'Icy;': 'И',
    'Idot;': 'İ',
    'Ifr;': 'ℑ',
    'Igrave': 'Ì',
    'Igrave;': 'Ì',
    'Im;': 'ℑ',
    'Imacr;': 'Ī',
    'ImaginaryI;': 'ⅈ',
    'Implies;': '⇒',
    'Int;': '∬',
    'Integral;': '∫',
    'Intersection;': '⋂',
    'InvisibleComma;': '\u2063',
    'InvisibleTimes;': '\u2062',
    'Iogon;': 'Į',
    'Iopf;': '𝕀',
    'Iota;': 'Ι',
    'Iscr;': 'ℐ',
    'Itilde;': 'Ĩ',
    'Iukcy;': 'І',
    'Iuml': 'Ï',
    'Iuml;': 'Ï',
    'Jcirc;': 'Ĵ',
    'Jcy;': 'Й',
    'Jfr;': '𝔍',
    'Jopf;': '𝕁',
    'Jscr;': '𝒥',
    'Jsercy;': 'Ј',
    'Jukcy;': 'Є',
    'KHcy;': 'Х',
    'KJcy;': 'Ќ',
    'Kappa;': 'Κ',
    'Kcedil;': 'Ķ',
    'Kcy;': 'К',
    'Kfr;': '𝔎',
    'Kopf;': '𝕂',
    'Kscr;': '𝒦',
    'LJcy;': 'Љ',
    'LT': '<',
    'LT;': '<',
    'Lacute;': 'Ĺ',
    'Lambda;': 'Λ',
    'Lang;': '⟪',
    'Laplacetrf;': 'ℒ',
    'Larr;': '↞',
    'Lcaron;': 'Ľ',
    'Lcedil;': 'Ļ',
    'Lcy;': 'Л',
    'LeftAngleBracket;': '⟨',
    'LeftArrow;': '←',
    'LeftArrowBar;': '⇤',
    'LeftArrowRightArrow;': '⇆',
    'LeftCeiling;': '⌈',
    'LeftDoubleBracket;': '⟦',
    'LeftDownTeeVector;': '⥡',
    'LeftDownVector;': '⇃',
    'LeftDownVectorBar;': '⥙',
    'LeftFloor;': '⌊',
    'LeftRightArrow;': '↔',
    'LeftRightVector;': '⥎',
    'LeftTee;': '⊣',
    'LeftTeeArrow;': '↤',
    'LeftTeeVector;': '⥚',
    'LeftTriangle;': '⊲',
    'LeftTriangleBar;': '⧏',
    'LeftTriangleEqual;': '⊴',
    'LeftUpDownVector;': '⥑',
    'LeftUpTeeVector;': '⥠',
    'LeftUpVector;': '↿',
    'LeftUpVectorBar;': '⥘',
    'LeftVector;': '↼',
    'LeftVectorBar;': '⥒',
    'Leftarrow;': '⇐',
    'Leftrightarrow;': '⇔',
    'LessEqualGreater;': '⋚',
    'LessFullEqual;': '≦',
    'LessGreater;': '≶',
    'LessLess;': '⪡',
    'LessSlantEqual;': '⩽',
    'LessTilde;': '≲',
    'Lfr;': '𝔏',
    'Ll;': '⋘',
    'Lleftarrow;': '⇚',
    'Lmidot;': 'Ŀ',
    'LongLeftArrow;': '⟵',
    'LongLeftRightArrow;': '⟷',
    'LongRightArrow;': '⟶',
    'Longleftarrow;': '⟸',
    'Longleftrightarrow;': '⟺',
    'Longrightarrow;': '⟹',
    'Lopf;': '𝕃',
    'LowerLeftArrow;': '↙',
    'LowerRightArrow;': '↘',
    'Lscr;': 'ℒ',
    'Lsh;': '↰',
    'Lstrok;': 'Ł',
    'Lt;': '≪',
    'Map;': '⤅',
    'Mcy;': 'М',
    'MediumSpace;': '\u205f',
    'Mellintrf;': 'ℳ',
    'Mfr;': '𝔐',
    'MinusPlus;': '∓',
    'Mopf;': '𝕄',
    'Mscr;': 'ℳ',
    'Mu;': 'Μ',
    'NJcy;': 'Њ',
    'Nacute;': 'Ń',
    'Ncaron;': 'Ň',
    'Ncedil;': 'Ņ',
    'Ncy;': 'Н',
    'NegativeMediumSpace;': '\u200b',
    'NegativeThickSpace;': '\u200b',
    'NegativeThinSpace;': '\u200b',
    'NegativeVeryThinSpace;': '\u200b',
    'NestedGreaterGreater;': '≫',
    'NestedLessLess;': '≪',
    'NewLine;': '\n',
    'Nfr;': '𝔑',
    'NoBreak;': '\u2060',
    'NonBreakingSpace;': '\xa0',
    'Nopf;': 'ℕ',
    'Not;': '⫬',
    'NotCongruent;': '≢',
    'NotCupCap;': '≭',
    'NotDoubleVerticalBar;': '∦',
    'NotElement;': '∉',
    'NotEqual;': '≠',
    'NotEqualTilde;': '≂̸',
    'NotExists;': '∄',
    'NotGreater;': '≯',
    'NotGreaterEqual;': '≱',
    'NotGreaterFullEqual;': '≧̸',
    'NotGreaterGreater;': '≫̸',
    'NotGreaterLess;': '≹',
    'NotGreaterSlantEqual;': '⩾̸',
    'NotGreaterTilde;': '≵',
    'NotHumpDownHump;': '≎̸',
    'NotHumpEqual;': '≏̸',
    'NotLeftTriangle;': '⋪',
    'NotLeftTriangleBar;': '⧏̸',
    'NotLeftTriangleEqual;': '⋬',
    'NotLess;': '≮',
    'NotLessEqual;': '≰',
    'NotLessGreater;': '≸',
    'NotLessLess;': '≪̸',
    'NotLessSlantEqual;': '⩽̸',
    'NotLessTilde;': '≴',
    'NotNestedGreaterGreater;': '⪢̸',
    'NotNestedLessLess;': '⪡̸',
    'NotPrecedes;': '⊀',
    'NotPrecedesEqual;': '⪯̸',
    'NotPrecedesSlantEqual;': '⋠',
    'NotReverseElement;': '∌',
    'NotRightTriangle;': '⋫',
    'NotRightTriangleBar;': '⧐̸',
    'NotRightTriangleEqual;': '⋭',
    'NotSquareSubset;': '⊏̸',
    'NotSquareSubsetEqual;': '⋢',
    'NotSquareSuperset;': '⊐̸',
    'NotSquareSupersetEqual;': '⋣',
    'NotSubset;': '⊂⃒',
    'NotSubsetEqual;': '⊈',
    'NotSucceeds;': '⊁',
    'NotSucceedsEqual;': '⪰̸',
    'NotSucceedsSlantEqual;': '⋡',
    'NotSucceedsTilde;': '≿̸',
    'NotSuperset;': '⊃⃒',
    'NotSupersetEqual;': '⊉',
    'NotTilde;': '≁',
    'NotTildeEqual;': '≄',
    'NotTildeFullEqual;': '≇',
    'NotTildeTilde;': '≉',
    'NotVerticalBar;': '∤',
    'Nscr;': '𝒩',
    'Ntilde': 'Ñ',
    'Ntilde;': 'Ñ',
    'Nu;': 'Ν',
    'OElig;': 'Œ',
    'Oacute': 'Ó',
    'Oacute;': 'Ó',
    'Ocirc': 'Ô',
    'Ocirc;': 'Ô',
    'Ocy;': 'О',
    'Odblac;': 'Ő',
    'Ofr;': '𝔒',
    'Ograve': 'Ò',
    'Ograve;': 'Ò',
    'Omacr;': 'Ō',
    'Omega;': 'Ω',
    'Omicron;': 'Ο',
    'Oopf;': '𝕆',
    'OpenCurlyDoubleQuote;': '“',
    'OpenCurlyQuote;': '‘',
    'Or;': '⩔',
    'Oscr;': '𝒪',
    'Oslash': 'Ø',
    'Oslash;': 'Ø',
    'Otilde': 'Õ',
    'Otilde;': 'Õ',
    'Otimes;': '⨷',
    'Ouml': 'Ö',
    'Ouml;': 'Ö',
    'OverBar;': '‾',
    'OverBrace;': '⏞',
    'OverBracket;': '⎴',
    'OverParenthesis;': '⏜',
    'PartialD;': '∂',
    'Pcy;': 'П',
    'Pfr;': '𝔓',
    'Phi;': 'Φ',
    'Pi;': 'Π',
    'PlusMinus;': '±',
    'Poincareplane;': 'ℌ',
    'Popf;': 'ℙ',
    'Pr;': '⪻',
    'Precedes;': '≺',
    'PrecedesEqual;': '⪯',
    'PrecedesSlantEqual;': '≼',
    'PrecedesTilde;': '≾',
    'Prime;': '″',
    'Product;': '∏',
    'Proportion;': '∷',
    'Proportional;': '∝',
    'Pscr;': '𝒫',
    'Psi;': 'Ψ',
    'QUOT': '"',
    'QUOT;': '"',
    'Qfr;': '𝔔',
    'Qopf;': 'ℚ',
    'Qscr;': '𝒬',
    'RBarr;': '⤐',
    'REG': '®',
    'REG;': '®',
    'Racute;': 'Ŕ',
    'Rang;': '⟫',
    'Rarr;': '↠',
    'Rarrtl;': '⤖',
    'Rcaron;': 'Ř',
    'Rcedil;': 'Ŗ',
    'Rcy;': 'Р',
    'Re;': 'ℜ',
    'ReverseElement;': '∋',
    'ReverseEquilibrium;': '⇋',
    'ReverseUpEquilibrium;': '⥯',
    'Rfr;': 'ℜ',
    'Rho;': 'Ρ',
    'RightAngleBracket;': '⟩',
    'RightArrow;': '→',
    'RightArrowBar;': '⇥',
    'RightArrowLeftArrow;': '⇄',
    'RightCeiling;': '⌉',
    'RightDoubleBracket;': '⟧',
    'RightDownTeeVector;': '⥝',
    'RightDownVector;': '⇂',
    'RightDownVectorBar;': '⥕',
    'RightFloor;': '⌋',
    'RightTee;': '⊢',
    'RightTeeArrow;': '↦',
    'RightTeeVector;': '⥛',
    'RightTriangle;': '⊳',
    'RightTriangleBar;': '⧐',
    'RightTriangleEqual;': '⊵',
    'RightUpDownVector;': '⥏',
    'RightUpTeeVector;': '⥜',
    'RightUpVector;': '↾',
    'RightUpVectorBar;': '⥔',
    'RightVector;': '⇀',
    'RightVectorBar;': '⥓',
    'Rightarrow;': '⇒',
    'Ropf;': 'ℝ',
    'RoundImplies;': '⥰',
    'Rrightarrow;': '⇛',
    'Rscr;': 'ℛ',
    'Rsh;': '↱',
    'RuleDelayed;': '⧴',
    'SHCHcy;': 'Щ',
    'SHcy;': 'Ш',
    'SOFTcy;': 'Ь',
    'Sacute;': 'Ś',
    'Sc;': '⪼',
    'Scaron;': 'Š',
    'Scedil;': 'Ş',
    'Scirc;': 'Ŝ',
    'Scy;': 'С',
    'Sfr;': '𝔖',
    'ShortDownArrow;': '↓',
    'ShortLeftArrow;': '←',
    'ShortRightArrow;': '→',
    'ShortUpArrow;': '↑',
    'Sigma;': 'Σ',
    'SmallCircle;': '∘',
    'Sopf;': '𝕊',
    'Sqrt;': '√',
    'Square;': '□',
    'SquareIntersection;': '⊓',
    'SquareSubset;': '⊏',
    'SquareSubsetEqual;': '⊑',
    'SquareSuperset;': '⊐',
    'SquareSupersetEqual;': '⊒',
    'SquareUnion;': '⊔',
    'Sscr;': '𝒮',
    'Star;': '⋆',
    'Sub;': '⋐',
    'Subset;': '⋐',
    'SubsetEqual;': '⊆',
    'Succeeds;': '≻',
    'SucceedsEqual;': '⪰',
    'SucceedsSlantEqual;': '≽',
    'SucceedsTilde;': '≿',
    'SuchThat;': '∋',
    'Sum;': '∑',
    'Sup;': '⋑',
    'Superset;': '⊃',
    'SupersetEqual;': '⊇',
    'Supset;': '⋑',
    'THORN': 'Þ',
    'THORN;': 'Þ',
    'TRADE;': '™',
    'TSHcy;': 'Ћ',
    'TScy;': 'Ц',
    'Tab;': '\t',
    'Tau;': 'Τ',
    'Tcaron;': 'Ť',
    'Tcedil;': 'Ţ',
    'Tcy;': 'Т',
    'Tfr;': '𝔗',
    'Therefore;': '∴',
    'Theta;': 'Θ',
    'ThickSpace;': '\u205f\u200a',
    'ThinSpace;': '\u2009',
    'Tilde;': '∼',
    'TildeEqual;': '≃',
    'TildeFullEqual;': '≅',
    'TildeTilde;': '≈',
    'Topf;': '𝕋',
    'TripleDot;': '⃛',
    'Tscr;': '𝒯',
    'Tstrok;': 'Ŧ',
    'Uacute': 'Ú',
    'Uacute;': 'Ú',
    'Uarr;': '↟',
    'Uarrocir;': '⥉',
    'Ubrcy;': 'Ў',
    'Ubreve;': 'Ŭ',
    'Ucirc': 'Û',
    'Ucirc;': 'Û',
    'Ucy;': 'У',
    'Udblac;': 'Ű',
    'Ufr;': '𝔘',
    'Ugrave': 'Ù',
    'Ugrave;': 'Ù',
    'Umacr;': 'Ū',
    'UnderBar;': '_',
    'UnderBrace;': '⏟',
    'UnderBracket;': '⎵',
    'UnderParenthesis;': '⏝',
    'Union;': '⋃',
    'UnionPlus;': '⊎',
    'Uogon;': 'Ų',
    'Uopf;': '𝕌',
    'UpArrow;': '↑',
    'UpArrowBar;': '⤒',
    'UpArrowDownArrow;': '⇅',
    'UpDownArrow;': '↕',
    'UpEquilibrium;': '⥮',
    'UpTee;': '⊥',
    'UpTeeArrow;': '↥',
    'Uparrow;': '⇑',
    'Updownarrow;': '⇕',
    'UpperLeftArrow;': '↖',
    'UpperRightArrow;': '↗',
    'Upsi;': 'ϒ',
    'Upsilon;': 'Υ',
    'Uring;': 'Ů',
    'Uscr;': '𝒰',
    'Utilde;': 'Ũ',
    'Uuml': 'Ü',
    'Uuml;': 'Ü',
    'VDash;': '⊫',
    'Vbar;': '⫫',
    'Vcy;': 'В',
    'Vdash;': '⊩',
    'Vdashl;': '⫦',
    'Vee;': '⋁',
    'Verbar;': '‖',
    'Vert;': '‖',
    'VerticalBar;': '∣',
    'VerticalLine;': '|',
    'VerticalSeparator;': '❘',
    'VerticalTilde;': '≀',
    'VeryThinSpace;': '\u200a',
    'Vfr;': '𝔙',
    'Vopf;': '𝕍',
    'Vscr;': '𝒱',
    'Vvdash;': '⊪',
    'Wcirc;': 'Ŵ',
    'Wedge;': '⋀',
    'Wfr;': '𝔚',
    'Wopf;': '𝕎',
    'Wscr;': '𝒲',
    'Xfr;': '𝔛',
    'Xi;': 'Ξ',
    'Xopf;': '𝕏',
    'Xscr;': '𝒳',
    'YAcy;': 'Я',
    'YIcy;': 'Ї',
    'YUcy;': 'Ю',
    'Yacute': 'Ý',
    'Yacute;': 'Ý',
    'Ycirc;': 'Ŷ',
    'Ycy;': 'Ы',
    'Yfr;': '𝔜',
    'Yopf;': '𝕐',
    'Yscr;': '𝒴',
    'Yuml;': 'Ÿ',
    'ZHcy;': 'Ж',
    'Zacute;': 'Ź',
    'Zcaron;': 'Ž',
    'Zcy;': 'З',
    'Zdot;': 'Ż',
    'ZeroWidthSpace;': '\u200b',
    'Zeta;': 'Ζ',
    'Zfr;': 'ℨ',
    'Zopf;': 'ℤ',
    'Zscr;': '𝒵',
    'aacute': 'á',
    'aacute;': 'á',
    'abreve;': 'ă',
    'ac;': '∾',
    'acE;': '∾̳',
    'acd;': '∿',
    'acirc': 'â',
    'acirc;': 'â',
    'acute': '´',
    'acute;': '´',
    'acy;': 'а',
    'aelig': 'æ',
    'aelig;': 'æ',
    'af;': '\u2061',
    'afr;': '𝔞',
    'agrave': 'à',
    'agrave;': 'à',
    'alefsym;': 'ℵ',
    'aleph;': 'ℵ',
    'alpha;': 'α',
    'amacr;': 'ā',
    'amalg;': '⨿',
    'amp': '&',
    'amp;': '&',
    'and;': '∧',
    'andand;': '⩕',
    'andd;': '⩜',
    'andslope;': '⩘',
    'andv;': '⩚',
    'ang;': '∠',
    'ange;': '⦤',
    'angle;': '∠',
    'angmsd;': '∡',
    'angmsdaa;': '⦨',
    'angmsdab;': '⦩',
    'angmsdac;': '⦪',
    'angmsdad;': '⦫',
    'angmsdae;': '⦬',
    'angmsdaf;': '⦭',
    'angmsdag;': '⦮',
    'angmsdah;': '⦯',
    'angrt;': '∟',
    'angrtvb;': '⊾',
    'angrtvbd;': '⦝',
    'angsph;': '∢',
    'angst;': 'Å',
    'angzarr;': '⍼',
    'aogon;': 'ą',
    'aopf;': '𝕒',
    'ap;': '≈',
    'apE;': '⩰',
    'apacir;': '⩯',
    'ape;': '≊',
    'apid;': '≋',
    'apos;': "'",
    'approx;': '≈',
    'approxeq;': '≊',
    'aring': 'å',
    'aring;': 'å',
    'ascr;': '𝒶',
    'ast;': '*',
    'asymp;': '≈',
    'asympeq;': '≍',
    'atilde': 'ã',
    'atilde;': 'ã',
    'auml': 'ä',
    'auml;': 'ä',
    'awconint;': '∳',
    'awint;': '⨑',
    'bNot;': '⫭',
    'backcong;': '≌',
    'backepsilon;': '϶',
    'backprime;': '‵',
    'backsim;': '∽',
    'backsimeq;': '⋍',
    'barvee;': '⊽',
    'barwed;': '⌅',
    'barwedge;': '⌅',
    'bbrk;': '⎵',
    'bbrktbrk;': '⎶',
    'bcong;': '≌',
    'bcy;': 'б',
    'bdquo;': '„',
    'becaus;': '∵',
    'because;': '∵',
    'bemptyv;': '⦰',
    'bepsi;': '϶',
    'bernou;': 'ℬ',
    'beta;': 'β',
    'beth;': 'ℶ',
    'between;': '≬',
    'bfr;': '𝔟',
    'bigcap;': '⋂',
    'bigcirc;': '◯',
    'bigcup;': '⋃',
    'bigodot;': '⨀',
    'bigoplus;': '⨁',
    'bigotimes;': '⨂',
    'bigsqcup;': '⨆',
    'bigstar;': '★',
    'bigtriangledown;': '▽',
    'bigtriangleup;': '△',
    'biguplus;': '⨄',
    'bigvee;': '⋁',
    'bigwedge;': '⋀',
    'bkarow;': '⤍',
    'blacklozenge;': '⧫',
    'blacksquare;': '▪',
    'blacktriangle;': '▴',
    'blacktriangledown;': '▾',
    'blacktriangleleft;': '◂',
    'blacktriangleright;': '▸',
    'blank;': '␣',
    'blk12;': '▒',
    'blk14;': '░',
    'blk34;': '▓',
    'block;': '█',
    'bne;': '=⃥',
    'bnequiv;': '≡⃥',
    'bnot;': '⌐',
    'bopf;': '𝕓',
    'bot;': '⊥',
    'bottom;': '⊥',
    'bowtie;': '⋈',
    'boxDL;': '╗',
    'boxDR;': '╔',
    'boxDl;': '╖',
    'boxDr;': '╓',
    'boxH;': '═',
    'boxHD;': '╦',
    'boxHU;': '╩',
    'boxHd;': '╤',
    'boxHu;': '╧',
    'boxUL;': '╝',
    'boxUR;': '╚',
    'boxUl;': '╜',
    'boxUr;': '╙',
    'boxV;': '║',
    'boxVH;': '╬',
    'boxVL;': '╣',
    'boxVR;': '╠',
    'boxVh;': '╫',
    'boxVl;': '╢',
    'boxVr;': '╟',
    'boxbox;': '⧉',
    'boxdL;': '╕',
    'boxdR;': '╒',
    'boxdl;': '┐',
    'boxdr;': '┌',
    'boxh;': '─',
    'boxhD;': '╥',
    'boxhU;': '╨',
    'boxhd;': '┬',
    'boxhu;': '┴',
    'boxminus;': '⊟',
    'boxplus;': '⊞',
    'boxtimes;': '⊠',
    'boxuL;': '╛',
    'boxuR;': '╘',
    'boxul;': '┘',
    'boxur;': '└',
    'boxv;': '│',
    'boxvH;': '╪',
    'boxvL;': '╡',
    'boxvR;': '╞',
    'boxvh;': '┼',
    'boxvl;': '┤',
    'boxvr;': '├',
    'bprime;': '‵',
    'breve;': '˘',
    'brvbar': '¦',
    'brvbar;': '¦',
    'bscr;': '𝒷',
    'bsemi;': '⁏',
    'bsim;': '∽',
    'bsime;': '⋍',
    'bsol;': '\\',
    'bsolb;': '⧅',
    'bsolhsub;': '⟈',
    'bull;': '•',
    'bullet;': '•',
    'bump;': '≎',
    'bumpE;': '⪮',
    'bumpe;': '≏',
    'bumpeq;': '≏',
    'cacute;': 'ć',
    'cap;': '∩',
    'capand;': '⩄',
    'capbrcup;': '⩉',
    'capcap;': '⩋',
    'capcup;': '⩇',
    'capdot;': '⩀',
    'caps;': '∩︀',
    'caret;': '⁁',
    'caron;': 'ˇ',
    'ccaps;': '⩍',
    'ccaron;': 'č',
    'ccedil': 'ç',
    'ccedil;': 'ç',
    'ccirc;': 'ĉ',
    'ccups;': '⩌',
    'ccupssm;': '⩐',
    'cdot;': 'ċ',
    'cedil': '¸',
    'cedil;': '¸',
    'cemptyv;': '⦲',
    'cent': '¢',
    'cent;': '¢',
    'centerdot;': '·',
    'cfr;': '𝔠',
    'chcy;': 'ч',
    'check;': '✓',
    'checkmark;': '✓',
    'chi;': 'χ',
    'cir;': '○',
    'cirE;': '⧃',
    'circ;': 'ˆ',
    'circeq;': '≗',
    'circlearrowleft;': '↺',
    'circlearrowright;': '↻',
    'circledR;': '®',
    'circledS;': 'Ⓢ',
    'circledast;': '⊛',
    'circledcirc;': '⊚',
    'circleddash;': '⊝',
    'cire;': '≗',
    'cirfnint;': '⨐',
    'cirmid;': '⫯',
    'cirscir;': '⧂',
    'clubs;': '♣',
    'clubsuit;': '♣',
    'colon;': ':',
    'colone;': '≔',
    'coloneq;': '≔',
    'comma;': ',',
    'commat;': '@',
    'comp;': '∁',
    'compfn;': '∘',
    'complement;': '∁',
    'complexes;': 'ℂ',
    'cong;': '≅',
    'congdot;': '⩭',
    'conint;': '∮',
    'copf;': '𝕔',
    'coprod;': '∐',
    'copy': '©',
    'copy;': '©',
    'copysr;': '℗',
    'crarr;': '↵',
    'cross;': '✗',
    'cscr;': '𝒸',
    'csub;': '⫏',
    'csube;': '⫑',
    'csup;': '⫐',
    'csupe;': '⫒',
    'ctdot;': '⋯',
    'cudarrl;': '⤸',
    'cudarrr;': '⤵',
    'cuepr;': '⋞',
    'cuesc;': '⋟',
    'cularr;': '↶',
    'cularrp;': '⤽',
    'cup;': '∪',
    'cupbrcap;': '⩈',
    'cupcap;': '⩆',
    'cupcup;': '⩊',
    'cupdot;': '⊍',
    'cupor;': '⩅',
    'cups;': '∪︀',
    'curarr;': '↷',
    'curarrm;': '⤼',
    'curlyeqprec;': '⋞',
    'curlyeqsucc;': '⋟',
    'curlyvee;': '⋎',
    'curlywedge;': '⋏',
    'curren': '¤',
    'curren;': '¤',
    'curvearrowleft;': '↶',
    'curvearrowright;': '↷',
    'cuvee;': '⋎',
    'cuwed;': '⋏',
    'cwconint;': '∲',
    'cwint;': '∱',
    'cylcty;': '⌭',
    'dArr;': '⇓',
    'dHar;': '⥥',
    'dagger;': '†',
    'daleth;': 'ℸ',
    'darr;': '↓',
    'dash;': '‐',
    'dashv;': '⊣',
    'dbkarow;': '⤏',
    'dblac;': '˝',
    'dcaron;': 'ď',
    'dcy;': 'д',
    'dd;': 'ⅆ',
    'ddagger;': '‡',
    'ddarr;': '⇊',
    'ddotseq;': '⩷',
    'deg': '°',
    'deg;': '°',
    'delta;': 'δ',
    'demptyv;': '⦱',
    'dfisht;': '⥿',
    'dfr;': '𝔡',
    'dharl;': '⇃',
    'dharr;': '⇂',
    'diam;': '⋄',
    'diamond;': '⋄',
    'diamondsuit;': '♦',
    'diams;': '♦',
    'die;': '¨',
    'digamma;': 'ϝ',
    'disin;': '⋲',
    'div;': '÷',
    'divide': '÷',
    'divide;': '÷',
    'divideontimes;': '⋇',
    'divonx;': '⋇',
    'djcy;': 'ђ',
    'dlcorn;': '⌞',
    'dlcrop;': '⌍',
    'dollar;': '$',
    'dopf;': '𝕕',
    'dot;': '˙',
    'doteq;': '≐',
    'doteqdot;': '≑',
    'dotminus;': '∸',
    'dotplus;': '∔',
    'dotsquare;': '⊡',
    'doublebarwedge;': '⌆',
    'downarrow;': '↓',
    'downdownarrows;': '⇊',
    'downharpoonleft;': '⇃',
    'downharpoonright;': '⇂',
    'drbkarow;': '⤐',
    'drcorn;': '⌟',
    'drcrop;': '⌌',
    'dscr;': '𝒹',
    'dscy;': 'ѕ',
    'dsol;': '⧶',
    'dstrok;': 'đ',
    'dtdot;': '⋱',
    'dtri;': '▿',
    'dtrif;': '▾',
    'duarr;': '⇵',
    'duhar;': '⥯',
    'dwangle;': '⦦',
    'dzcy;': 'џ',
    'dzigrarr;': '⟿',
    'eDDot;': '⩷',
    'eDot;': '≑',
    'eacute': 'é',
    'eacute;': 'é',
    'easter;': '⩮',
    'ecaron;': 'ě',
    'ecir;': '≖',
    'ecirc': 'ê',
    'ecirc;': 'ê',
    'ecolon;': '≕',
    'ecy;': 'э',
    'edot;': 'ė',
    'ee;': 'ⅇ',
    'efDot;': '≒',
    'efr;': '𝔢',
    'eg;': '⪚',
    'egrave': 'è',
    'egrave;': 'è',
    'egs;': '⪖',
    'egsdot;': '⪘',
    'el;': '⪙',
    'elinters;': '⏧',
    'ell;': 'ℓ',
    'els;': '⪕',
    'elsdot;': '⪗',
    'emacr;': 'ē',
    'empty;': '∅',
    'emptyset;': '∅',
    'emptyv;': '∅',
    'emsp13;': '\u2004',
    'emsp14;': '\u2005',
    'emsp;': '\u2003',
    'eng;': 'ŋ',
    'ensp;': '\u2002',
    'eogon;': 'ę',
    'eopf;': '𝕖',
    'epar;': '⋕',
    'eparsl;': '⧣',
    'eplus;': '⩱',
    'epsi;': 'ε',
    'epsilon;': 'ε',
    'epsiv;': 'ϵ',
    'eqcirc;': '≖',
    'eqcolon;': '≕',
    'eqsim;': '≂',
    'eqslantgtr;': '⪖',
    'eqslantless;': '⪕',
    'equals;': '=',
    'equest;': '≟',
    'equiv;': '≡',
    'equivDD;': '⩸',
    'eqvparsl;': '⧥',
    'erDot;': '≓',
    'erarr;': '⥱',
    'escr;': 'ℯ',
    'esdot;': '≐',
    'esim;': '≂',
    'eta;': 'η',
    'eth': 'ð',
    'eth;': 'ð',
    'euml': 'ë',
    'euml;': 'ë',
    'euro;': '€',
    'excl;': '!',
    'exist;': '∃',
    'expectation;': 'ℰ',
    'exponentiale;': 'ⅇ',
    'fallingdotseq;': '≒',
    'fcy;': 'ф',
    'female;': '♀',
    'ffilig;': 'ﬃ',
    'fflig;': 'ﬀ',
    'ffllig;': 'ﬄ',
    'ffr;': '𝔣',
    'filig;': 'ﬁ',
    'fjlig;': 'fj',
    'flat;': '♭',
    'fllig;': 'ﬂ',
    'fltns;': '▱',
    'fnof;': 'ƒ',
    'fopf;': '𝕗',
    'forall;': '∀',
    'fork;': '⋔',
    'forkv;': '⫙',
    'fpartint;': '⨍',
    'frac12': '½',
    'frac12;': '½',
    'frac13;': '⅓',
    'frac14': '¼',
    'frac14;': '¼',
    'frac15;': '⅕',
    'frac16;': '⅙',
    'frac18;': '⅛',
    'frac23;': '⅔',
    'frac25;': '⅖',
    'frac34': '¾',
    'frac34;': '¾',
    'frac35;': '⅗',
    'frac38;': '⅜',
    'frac45;': '⅘',
    'frac56;': '⅚',
    'frac58;': '⅝',
    'frac78;': '⅞',
    'frasl;': '⁄',
    'frown;': '⌢',
    'fscr;': '𝒻',
    'gE;': '≧',
    'gEl;': '⪌',
    'gacute;': 'ǵ',
    'gamma;': 'γ',
    'gammad;': 'ϝ',
    'gap;': '⪆',
    'gbreve;': 'ğ',
    'gcirc;': 'ĝ',
    'gcy;': 'г',
    'gdot;': 'ġ',
    'ge;': '≥',
    'gel;': '⋛',
    'geq;': '≥',
    'geqq;': '≧',
    'geqslant;': '⩾',
    'ges;': '⩾',
    'gescc;': '⪩',
    'gesdot;': '⪀',
    'gesdoto;': '⪂',
    'gesdotol;': '⪄',
    'gesl;': '⋛︀',
    'gesles;': '⪔',
    'gfr;': '𝔤',
    'gg;': '≫',
    'ggg;': '⋙',
    'gimel;': 'ℷ',
    'gjcy;': 'ѓ',
    'gl;': '≷',
    'glE;': '⪒',
    'gla;': '⪥',
    'glj;': '⪤',
    'gnE;': '≩',
    'gnap;': '⪊',
    'gnapprox;': '⪊',
    'gne;': '⪈',
    'gneq;': '⪈',
    'gneqq;': '≩',
    'gnsim;': '⋧',
    'gopf;': '𝕘',
    'grave;': '`',
    'gscr;': 'ℊ',
    'gsim;': '≳',
    'gsime;': '⪎',
    'gsiml;': '⪐',
    'gt': '>',
    'gt;': '>',
    'gtcc;': '⪧',
    'gtcir;': '⩺',
    'gtdot;': '⋗',
    'gtlPar;': '⦕',
    'gtquest;': '⩼',
    'gtrapprox;': '⪆',
    'gtrarr;': '⥸',
    'gtrdot;': '⋗',
    'gtreqless;': '⋛',
    'gtreqqless;': '⪌',
    'gtrless;': '≷',
    'gtrsim;': '≳',
    'gvertneqq;': '≩︀',
    'gvnE;': '≩︀',
    'hArr;': '⇔',
    'hairsp;': '\u200a',
    'half;': '½',
    'hamilt;': 'ℋ',
    'hardcy;': 'ъ',
    'harr;': '↔',
    'harrcir;': '⥈',
    'harrw;': '↭',
    'hbar;': 'ℏ',
    'hcirc;': 'ĥ',
    'hearts;': '♥',
    'heartsuit;': '♥',
    'hellip;': '…',
    'hercon;': '⊹',
    'hfr;': '𝔥',
    'hksearow;': '⤥',
    'hkswarow;': '⤦',
    'hoarr;': '⇿',
    'homtht;': '∻',
    'hookleftarrow;': '↩',
    'hookrightarrow;': '↪',
    'hopf;': '𝕙',
    'horbar;': '―',
    'hscr;': '𝒽',
    'hslash;': 'ℏ',
    'hstrok;': 'ħ',
    'hybull;': '⁃',
    'hyphen;': '‐',
    'iacute': 'í',
    'iacute;': 'í',
    'ic;': '\u2063',
    'icirc': 'î',
    'icirc;': 'î',
    'icy;': 'и',
    'iecy;': 'е',
    'iexcl': '¡',
    'iexcl;': '¡',
    'iff;': '⇔',
    'ifr;': '𝔦',
    'igrave': 'ì',
    'igrave;': 'ì',
    'ii;': 'ⅈ',
    'iiiint;': '⨌',
    'iiint;': '∭',
    'iinfin;': '⧜',
    'iiota;': '℩',
    'ijlig;': 'ĳ',
    'imacr;': 'ī',
    'image;': 'ℑ',
    'imagline;': 'ℐ',
    'imagpart;': 'ℑ',
    'imath;': 'ı',
    'imof;': '⊷',
    'imped;': 'Ƶ',
    'in;': '∈',
    'incare;': '℅',
    'infin;': '∞',
    'infintie;': '⧝',
    'inodot;': 'ı',
    'int;': '∫',
    'intcal;': '⊺',
    'integers;': 'ℤ',
    'intercal;': '⊺',
    'intlarhk;': '⨗',
    'intprod;': '⨼',
    'iocy;': 'ё',
    'iogon;': 'į',
    'iopf;': '𝕚',
    'iota;': 'ι',
    'iprod;': '⨼',
    'iquest': '¿',
    'iquest;': '¿',
    'iscr;': '𝒾',
    'isin;': '∈',
    'isinE;': '⋹',
    'isindot;': '⋵',
    'isins;': '⋴',
    'isinsv;': '⋳',
    'isinv;': '∈',
    'it;': '\u2062',
    'itilde;': 'ĩ',
    'iukcy;': 'і',
    'iuml': 'ï',
    'iuml;': 'ï',
    'jcirc;': 'ĵ',
    'jcy;': 'й',
    'jfr;': '𝔧',
    'jmath;': 'ȷ',
    'jopf;': '𝕛',
    'jscr;': '𝒿',
    'jsercy;': 'ј',
    'jukcy;': 'є',
    'kappa;': 'κ',
    'kappav;': 'ϰ',
    'kcedil;': 'ķ',
    'kcy;': 'к',
    'kfr;': '𝔨',
    'kgreen;': 'ĸ',
    'khcy;': 'х',
    'kjcy;': 'ќ',
    'kopf;': '𝕜',
    'kscr;': '𝓀',
    'lAarr;': '⇚',
    'lArr;': '⇐',
    'lAtail;': '⤛',
    'lBarr;': '⤎',
    'lE;': '≦',
    'lEg;': '⪋',
    'lHar;': '⥢',
    'lacute;': 'ĺ',
    'laemptyv;': '⦴',
    'lagran;': 'ℒ',
    'lambda;': 'λ',
    'lang;': '⟨',
    'langd;': '⦑',
    'langle;': '⟨',
    'lap;': '⪅',
    'laquo': '«',
    'laquo;': '«',
    'larr;': '←',
    'larrb;': '⇤',
    'larrbfs;': '⤟',
    'larrfs;': '⤝',
    'larrhk;': '↩',
    'larrlp;': '↫',
    'larrpl;': '⤹',
    'larrsim;': '⥳',
    'larrtl;': '↢',
    'lat;': '⪫',
    'latail;': '⤙',
    'late;': '⪭',
    'lates;': '⪭︀',
    'lbarr;': '⤌',
    'lbbrk;': '❲',
    'lbrace;': '{',
    'lbrack;': '[',
    'lbrke;': '⦋',
    'lbrksld;': '⦏',
    'lbrkslu;': '⦍',
    'lcaron;': 'ľ',
    'lcedil;': 'ļ',
    'lceil;': '⌈',
    'lcub;': '{',
    'lcy;': 'л',
    'ldca;': '⤶',
    'ldquo;': '“',
    'ldquor;': '„',
    'ldrdhar;': '⥧',
    'ldrushar;': '⥋',
    'ldsh;': '↲',
    'le;': '≤',
    'leftarrow;': '←',
    'leftarrowtail;': '↢',
    'leftharpoondown;': '↽',
    'leftharpoonup;': '↼',
    'leftleftarrows;': '⇇',
    'leftrightarrow;': '↔',
    'leftrightarrows;': '⇆',
    'leftrightharpoons;': '⇋',
    'leftrightsquigarrow;': '↭',
    'leftthreetimes;': '⋋',
    'leg;': '⋚',
    'leq;': '≤',
    'leqq;': '≦',
    'leqslant;': '⩽',
    'les;': '⩽',
    'lescc;': '⪨',
    'lesdot;': '⩿',
    'lesdoto;': '⪁',
    'lesdotor;': '⪃',
    'lesg;': '⋚︀',
    'lesges;': '⪓',
    'lessapprox;': '⪅',
    'lessdot;': '⋖',
    'lesseqgtr;': '⋚',
    'lesseqqgtr;': '⪋',
    'lessgtr;': '≶',
    'lesssim;': '≲',
    'lfisht;': '⥼',
    'lfloor;': '⌊',
    'lfr;': '𝔩',
    'lg;': '≶',
    'lgE;': '⪑',
    'lhard;': '↽',
    'lharu;': '↼',
    'lharul;': '⥪',
    'lhblk;': '▄',
    'ljcy;': 'љ',
    'll;': '≪',
    'llarr;': '⇇',
    'llcorner;': '⌞',
    'llhard;': '⥫',
    'lltri;': '◺',
    'lmidot;': 'ŀ',
    'lmoust;': '⎰',
    'lmoustache;': '⎰',
    'lnE;': '≨',
    'lnap;': '⪉',
    'lnapprox;': '⪉',
    'lne;': '⪇',
    'lneq;': '⪇',
    'lneqq;': '≨',
    'lnsim;': '⋦',
    'loang;': '⟬',
    'loarr;': '⇽',
    'lobrk;': '⟦',
    'longleftarrow;': '⟵',
    'longleftrightarrow;': '⟷',
    'longmapsto;': '⟼',
    'longrightarrow;': '⟶',
    'looparrowleft;': '↫',
    'looparrowright;': '↬',
    'lopar;': '⦅',
    'lopf;': '𝕝',
    'loplus;': '⨭',
    'lotimes;': '⨴',
    'lowast;': '∗',
    'lowbar;': '_',
    'loz;': '◊',
    'lozenge;': '◊',
    'lozf;': '⧫',
    'lpar;': '(',
    'lparlt;': '⦓',
    'lrarr;': '⇆',
    'lrcorner;': '⌟',
    'lrhar;': '⇋',
    'lrhard;': '⥭',
    'lrm;': '\u200e',
    'lrtri;': '⊿',
    'lsaquo;': '‹',
    'lscr;': '𝓁',
    'lsh;': '↰',
    'lsim;': '≲',
    'lsime;': '⪍',
    'lsimg;': '⪏',
    'lsqb;': '[',
    'lsquo;': '‘',
    'lsquor;': '‚',
    'lstrok;': 'ł',
    'lt': '<',
    'lt;': '<',
    'ltcc;': '⪦',
    'ltcir;': '⩹',
    'ltdot;': '⋖',
    'lthree;': '⋋',
    'ltimes;': '⋉',
    'ltlarr;': '⥶',
    'ltquest;': '⩻',
    'ltrPar;': '⦖',
    'ltri;': '◃',
    'ltrie;': '⊴',
    'ltrif;': '◂',
    'lurdshar;': '⥊',
    'luruhar;': '⥦',
    'lvertneqq;': '≨︀',
    'lvnE;': '≨︀',
    'mDDot;': '∺',
    'macr': '¯',
    'macr;': '¯',
    'male;': '♂',
    'malt;': '✠',
    'maltese;': '✠',
    'map;': '↦',
    'mapsto;': '↦',
    'mapstodown;': '↧',
    'mapstoleft;': '↤',
    'mapstoup;': '↥',
    'marker;': '▮',
    'mcomma;': '⨩',
    'mcy;': 'м',
    'mdash;': '—',
    'measuredangle;': '∡',
    'mfr;': '𝔪',
    'mho;': '℧',
    'micro': 'µ',
    'micro;': 'µ',
    'mid;': '∣',
    'midast;': '*',
    'midcir;': '⫰',
    'middot': '·',
    'middot;': '·',
    'minus;': '−',
    'minusb;': '⊟',
    'minusd;': '∸',
    'minusdu;': '⨪',
    'mlcp;': '⫛',
    'mldr;': '…',
    'mnplus;': '∓',
    'models;': '⊧',
    'mopf;': '𝕞',
    'mp;': '∓',
    'mscr;': '𝓂',
    'mstpos;': '∾',
    'mu;': 'μ',
    'multimap;': '⊸',
    'mumap;': '⊸',
    'nGg;': '⋙̸',
    'nGt;': '≫⃒',
    'nGtv;': '≫̸',
    'nLeftarrow;': '⇍',
    'nLeftrightarrow;': '⇎',
    'nLl;': '⋘̸',
    'nLt;': '≪⃒',
    'nLtv;': '≪̸',
    'nRightarrow;': '⇏',
    'nVDash;': '⊯',
    'nVdash;': '⊮',
    'nabla;': '∇',
    'nacute;': 'ń',
    'nang;': '∠⃒',
    'nap;': '≉',
    'napE;': '⩰̸',
    'napid;': '≋̸',
    'napos;': 'ŉ',
    'napprox;': '≉',
    'natur;': '♮',
    'natural;': '♮',
    'naturals;': 'ℕ',
    'nbsp': '\xa0',
    'nbsp;': '\xa0',
    'nbump;': '≎̸',
    'nbumpe;': '≏̸',
    'ncap;': '⩃',
    'ncaron;': 'ň',
    'ncedil;': 'ņ',
    'ncong;': '≇',
    'ncongdot;': '⩭̸',
    'ncup;': '⩂',
    'ncy;': 'н',
    'ndash;': '–',
    'ne;': '≠',
    'neArr;': '⇗',
    'nearhk;': '⤤',
    'nearr;': '↗',
    'nearrow;': '↗',
    'nedot;': '≐̸',
    'nequiv;': '≢',
    'nesear;': '⤨',
    'nesim;': '≂̸',
    'nexist;': '∄',
    'nexists;': '∄',
    'nfr;': '𝔫',
    'ngE;': '≧̸',
    'nge;': '≱',
    'ngeq;': '≱',
    'ngeqq;': '≧̸',
    'ngeqslant;': '⩾̸',
    'nges;': '⩾̸',
    'ngsim;': '≵',
    'ngt;': '≯',
    'ngtr;': '≯',
    'nhArr;': '⇎',
    'nharr;': '↮',
    'nhpar;': '⫲',
    'ni;': '∋',
    'nis;': '⋼',
    'nisd;': '⋺',
    'niv;': '∋',
    'njcy;': 'њ',
    'nlArr;': '⇍',
    'nlE;': '≦̸',
    'nlarr;': '↚',
    'nldr;': '‥',
    'nle;': '≰',
    'nleftarrow;': '↚',
    'nleftrightarrow;': '↮',
    'nleq;': '≰',
    'nleqq;': '≦̸',
    'nleqslant;': '⩽̸',
    'nles;': '⩽̸',
    'nless;': '≮',
    'nlsim;': '≴',
    'nlt;': '≮',
    'nltri;': '⋪',
    'nltrie;': '⋬',
    'nmid;': '∤',
    'nopf;': '𝕟',
    'not': '¬',
    'not;': '¬',
    'notin;': '∉',
    'notinE;': '⋹̸',
    'notindot;': '⋵̸',
    'notinva;': '∉',
    'notinvb;': '⋷',
    'notinvc;': '⋶',
    'notni;': '∌',
    'notniva;': '∌',
    'notnivb;': '⋾',
    'notnivc;': '⋽',
    'npar;': '∦',
    'nparallel;': '∦',
    'nparsl;': '⫽⃥',
    'npart;': '∂̸',
    'npolint;': '⨔',
    'npr;': '⊀',
    'nprcue;': '⋠',
    'npre;': '⪯̸',
    'nprec;': '⊀',
    'npreceq;': '⪯̸',
    'nrArr;': '⇏',
    'nrarr;': '↛',
    'nrarrc;': '⤳̸',
    'nrarrw;': '↝̸',
    'nrightarrow;': '↛',
    'nrtri;': '⋫',
    'nrtrie;': '⋭',
    'nsc;': '⊁',
    'nsccue;': '⋡',
    'nsce;': '⪰̸',
    'nscr;': '𝓃',
    'nshortmid;': '∤',
    'nshortparallel;': '∦',
    'nsim;': '≁',
    'nsime;': '≄',
    'nsimeq;': '≄',
    'nsmid;': '∤',
    'nspar;': '∦',
    'nsqsube;': '⋢',
    'nsqsupe;': '⋣',
    'nsub;': '⊄',
    'nsubE;': '⫅̸',
    'nsube;': '⊈',
    'nsubset;': '⊂⃒',
    'nsubseteq;': '⊈',
    'nsubseteqq;': '⫅̸',
    'nsucc;': '⊁',
    'nsucceq;': '⪰̸',
    'nsup;': '⊅',
    'nsupE;': '⫆̸',
    'nsupe;': '⊉',
    'nsupset;': '⊃⃒',
    'nsupseteq;': '⊉',
    'nsupseteqq;': '⫆̸',
    'ntgl;': '≹',
    'ntilde': 'ñ',
    'ntilde;': 'ñ',
    'ntlg;': '≸',
    'ntriangleleft;': '⋪',
    'ntrianglelefteq;': '⋬',
    'ntriangleright;': '⋫',
    'ntrianglerighteq;': '⋭',
    'nu;': 'ν',
    'num;': '#',
    'numero;': '№',
    'numsp;': '\u2007',
    'nvDash;': '⊭',
    'nvHarr;': '⤄',
    'nvap;': '≍⃒',
    'nvdash;': '⊬',
    'nvge;': '≥⃒',
    'nvgt;': '>⃒',
    'nvinfin;': '⧞',
    'nvlArr;': '⤂',
    'nvle;': '≤⃒',
    'nvlt;': '<⃒',
    'nvltrie;': '⊴⃒',
    'nvrArr;': '⤃',
    'nvrtrie;': '⊵⃒',
    'nvsim;': '∼⃒',
    'nwArr;': '⇖',
    'nwarhk;': '⤣',
    'nwarr;': '↖',
    'nwarrow;': '↖',
    'nwnear;': '⤧',
    'oS;': 'Ⓢ',
    'oacute': 'ó',
    'oacute;': 'ó',
    'oast;': '⊛',
    'ocir;': '⊚',
    'ocirc': 'ô',
    'ocirc;': 'ô',
    'ocy;': 'о',
    'odash;': '⊝',
    'odblac;': 'ő',
    'odiv;': '⨸',
    'odot;': '⊙',
    'odsold;': '⦼',
    'oelig;': 'œ',
    'ofcir;': '⦿',
    'ofr;': '𝔬',
    'ogon;': '˛',
    'ograve': 'ò',
    'ograve;': 'ò',
    'ogt;': '⧁',
    'ohbar;': '⦵',
    'ohm;': 'Ω',
    'oint;': '∮',
    'olarr;': '↺',
    'olcir;': '⦾',
    'olcross;': '⦻',
    'oline;': '‾',
    'olt;': '⧀',
    'omacr;': 'ō',
    'omega;': 'ω',
    'omicron;': 'ο',
    'omid;': '⦶',
    'ominus;': '⊖',
    'oopf;': '𝕠',
    'opar;': '⦷',
    'operp;': '⦹',
    'oplus;': '⊕',
    'or;': '∨',
    'orarr;': '↻',
    'ord;': '⩝',
    'order;': 'ℴ',
    'orderof;': 'ℴ',
    'ordf': 'ª',
    'ordf;': 'ª',
    'ordm': 'º',
    'ordm;': 'º',
    'origof;': '⊶',
    'oror;': '⩖',
    'orslope;': '⩗',
    'orv;': '⩛',
    'oscr;': 'ℴ',
    'oslash': 'ø',
    'oslash;': 'ø',
    'osol;': '⊘',
    'otilde': 'õ',
    'otilde;': 'õ',
    'otimes;': '⊗',
    'otimesas;': '⨶',
    'ouml': 'ö',
    'ouml;': 'ö',
    'ovbar;': '⌽',
    'par;': '∥',
    'para': '¶',
    'para;': '¶',
    'parallel;': '∥',
    'parsim;': '⫳',
    'parsl;': '⫽',
    'part;': '∂',
    'pcy;': 'п',
    'percnt;': '%',
    'period;': '.',
    'permil;': '‰',
    'perp;': '⊥',
    'pertenk;': '‱',
    'pfr;': '𝔭',
    'phi;': 'φ',
    'phiv;': 'ϕ',
    'phmmat;': 'ℳ',
    'phone;': '☎',
    'pi;': 'π',
    'pitchfork;': '⋔',
    'piv;': 'ϖ',
    'planck;': 'ℏ',
    'planckh;': 'ℎ',
    'plankv;': 'ℏ',
    'plus;': '+',
    'plusacir;': '⨣',
    'plusb;': '⊞',
    'pluscir;': '⨢',
    'plusdo;': '∔',
    'plusdu;': '⨥',
    'pluse;': '⩲',
    'plusmn': '±',
    'plusmn;': '±',
    'plussim;': '⨦',
    'plustwo;': '⨧',
    'pm;': '±',
    'pointint;': '⨕',
    'popf;': '𝕡',
    'pound': '£',
    'pound;': '£',
    'pr;': '≺',
    'prE;': '⪳',
    'prap;': '⪷',
    'prcue;': '≼',
    'pre;': '⪯',
    'prec;': '≺',
    'precapprox;': '⪷',
    'preccurlyeq;': '≼',
    'preceq;': '⪯',
    'precnapprox;': '⪹',
    'precneqq;': '⪵',
    'precnsim;': '⋨',
    'precsim;': '≾',
    'prime;': '′',
    'primes;': 'ℙ',
    'prnE;': '⪵',
    'prnap;': '⪹',
    'prnsim;': '⋨',
    'prod;': '∏',
    'profalar;': '⌮',
    'profline;': '⌒',
    'profsurf;': '⌓',
    'prop;': '∝',
    'propto;': '∝',
    'prsim;': '≾',
    'prurel;': '⊰',
    'pscr;': '𝓅',
    'psi;': 'ψ',
    'puncsp;': '\u2008',
    'qfr;': '𝔮',
    'qint;': '⨌',
    'qopf;': '𝕢',
    'qprime;': '⁗',
    'qscr;': '𝓆',
    'quaternions;': 'ℍ',
    'quatint;': '⨖',
    'quest;': '?',
    'questeq;': '≟',
    'quot': '"',
    'quot;': '"',
    'rAarr;': '⇛',
    'rArr;': '⇒',
    'rAtail;': '⤜',
    'rBarr;': '⤏',
    'rHar;': '⥤',
    'race;': '∽̱',
    'racute;': 'ŕ',
    'radic;': '√',
    'raemptyv;': '⦳',
    'rang;': '⟩',
    'rangd;': '⦒',
    'range;': '⦥',
    'rangle;': '⟩',
    'raquo': '»',
    'raquo;': '»',
    'rarr;': '→',
    'rarrap;': '⥵',
    'rarrb;': '⇥',
    'rarrbfs;': '⤠',
    'rarrc;': '⤳',
    'rarrfs;': '⤞',
    'rarrhk;': '↪',
    'rarrlp;': '↬',
    'rarrpl;': '⥅',
    'rarrsim;': '⥴',
    'rarrtl;': '↣',
    'rarrw;': '↝',
    'ratail;': '⤚',
    'ratio;': '∶',
    'rationals;': 'ℚ',
    'rbarr;': '⤍',
    'rbbrk;': '❳',
    'rbrace;': '}',
    'rbrack;': ']',
    'rbrke;': '⦌',
    'rbrksld;': '⦎',
    'rbrkslu;': '⦐',
    'rcaron;': 'ř',
    'rcedil;': 'ŗ',
    'rceil;': '⌉',
    'rcub;': '}',
    'rcy;': 'р',
    'rdca;': '⤷',
    'rdldhar;': '⥩',
    'rdquo;': '”',
    'rdquor;': '”',
    'rdsh;': '↳',
    'real;': 'ℜ',
    'realine;': 'ℛ',
    'realpart;': 'ℜ',
    'reals;': 'ℝ',
    'rect;': '▭',
    'reg': '®',
    'reg;': '®',
    'rfisht;': '⥽',
    'rfloor;': '⌋',
    'rfr;': '𝔯',
    'rhard;': '⇁',
    'rharu;': '⇀',
    'rharul;': '⥬',
    'rho;': 'ρ',
    'rhov;': 'ϱ',
    'rightarrow;': '→',
    'rightarrowtail;': '↣',
    'rightharpoondown;': '⇁',
    'rightharpoonup;': '⇀',
    'rightleftarrows;': '⇄',
    'rightleftharpoons;': '⇌',
    'rightrightarrows;': '⇉',
    'rightsquigarrow;': '↝',
    'rightthreetimes;': '⋌',
    'ring;': '˚',
    'risingdotseq;': '≓',
    'rlarr;': '⇄',
    'rlhar;': '⇌',
    'rlm;': '\u200f',
    'rmoust;': '⎱',
    'rmoustache;': '⎱',
    'rnmid;': '⫮',
    'roang;': '⟭',
    'roarr;': '⇾',
    'robrk;': '⟧',
    'ropar;': '⦆',
    'ropf;': '𝕣',
    'roplus;': '⨮',
    'rotimes;': '⨵',
    'rpar;': ')',
    'rpargt;': '⦔',
    'rppolint;': '⨒',
    'rrarr;': '⇉',
    'rsaquo;': '›',
    'rscr;': '𝓇',
    'rsh;': '↱',
    'rsqb;': ']',
    'rsquo;': '’',
    'rsquor;': '’',
    'rthree;': '⋌',
    'rtimes;': '⋊',
    'rtri;': '▹',
    'rtrie;': '⊵',
    'rtrif;': '▸',
    'rtriltri;': '⧎',
    'ruluhar;': '⥨',
    'rx;': '℞',
    'sacute;': 'ś',
    'sbquo;': '‚',
    'sc;': '≻',
    'scE;': '⪴',
    'scap;': '⪸',
    'scaron;': 'š',
    'sccue;': '≽',
    'sce;': '⪰',
    'scedil;': 'ş',
    'scirc;': 'ŝ',
    'scnE;': '⪶',
    'scnap;': '⪺',
    'scnsim;': '⋩',
    'scpolint;': '⨓',
    'scsim;': '≿',
    'scy;': 'с',
    'sdot;': '⋅',
    'sdotb;': '⊡',
    'sdote;': '⩦',
    'seArr;': '⇘',
    'searhk;': '⤥',
    'searr;': '↘',
    'searrow;': '↘',
    'sect': '§',
    'sect;': '§',
    'semi;': ';',
    'seswar;': '⤩',
    'setminus;': '∖',
    'setmn;': '∖',
    'sext;': '✶',
    'sfr;': '𝔰',
    'sfrown;': '⌢',
    'sharp;': '♯',
    'shchcy;': 'щ',
    'shcy;': 'ш',
    'shortmid;': '∣',
    'shortparallel;': '∥',
    'shy': '\xad',
    'shy;': '\xad',
    'sigma;': 'σ',
    'sigmaf;': 'ς',
    'sigmav;': 'ς',
    'sim;': '∼',
    'simdot;': '⩪',
    'sime;': '≃',
    'simeq;': '≃',
    'simg;': '⪞',
    'simgE;': '⪠',
    'siml;': '⪝',
    'simlE;': '⪟',
    'simne;': '≆',
    'simplus;': '⨤',
    'simrarr;': '⥲',
    'slarr;': '←',
    'smallsetminus;': '∖',
    'smashp;': '⨳',
    'smeparsl;': '⧤',
    'smid;': '∣',
    'smile;': '⌣',
    'smt;': '⪪',
    'smte;': '⪬',
    'smtes;': '⪬︀',
    'softcy;': 'ь',
    'sol;': '/',
    'solb;': '⧄',
    'solbar;': '⌿',
    'sopf;': '𝕤',
    'spades;': '♠',
    'spadesuit;': '♠',
    'spar;': '∥',
    'sqcap;': '⊓',
    'sqcaps;': '⊓︀',
    'sqcup;': '⊔',
    'sqcups;': '⊔︀',
    'sqsub;': '⊏',
    'sqsube;': '⊑',
    'sqsubset;': '⊏',
    'sqsubseteq;': '⊑',
    'sqsup;': '⊐',
    'sqsupe;': '⊒',
    'sqsupset;': '⊐',
    'sqsupseteq;': '⊒',
    'squ;': '□',
    'square;': '□',
    'squarf;': '▪',
    'squf;': '▪',
    'srarr;': '→',
    'sscr;': '𝓈',
    'ssetmn;': '∖',
    'ssmile;': '⌣',
    'sstarf;': '⋆',
    'star;': '☆',
    'starf;': '★',
    'straightepsilon;': 'ϵ',
    'straightphi;': 'ϕ',
    'strns;': '¯',
    'sub;': '⊂',
    'subE;': '⫅',
    'subdot;': '⪽',
    'sube;': '⊆',
    'subedot;': '⫃',
    'submult;': '⫁',
    'subnE;': '⫋',
    'subne;': '⊊',
    'subplus;': '⪿',
    'subrarr;': '⥹',
    'subset;': '⊂',
    'subseteq;': '⊆',
    'subseteqq;': '⫅',
    'subsetneq;': '⊊',
    'subsetneqq;': '⫋',
    'subsim;': '⫇',
    'subsub;': '⫕',
    'subsup;': '⫓',
    'succ;': '≻',
    'succapprox;': '⪸',
    'succcurlyeq;': '≽',
    'succeq;': '⪰',
    'succnapprox;': '⪺',
    'succneqq;': '⪶',
    'succnsim;': '⋩',
    'succsim;': '≿',
    'sum;': '∑',
    'sung;': '♪',
    'sup1': '¹',
    'sup1;': '¹',
    'sup2': '²',
    'sup2;': '²',
    'sup3': '³',
    'sup3;': '³',
    'sup;': '⊃',
    'supE;': '⫆',
    'supdot;': '⪾',
    'supdsub;': '⫘',
    'supe;': '⊇',
    'supedot;': '⫄',
    'suphsol;': '⟉',
    'suphsub;': '⫗',
    'suplarr;': '⥻',
    'supmult;': '⫂',
    'supnE;': '⫌',
    'supne;': '⊋',
    'supplus;': '⫀',
    'supset;': '⊃',
    'supseteq;': '⊇',
    'supseteqq;': '⫆',
    'supsetneq;': '⊋',
    'supsetneqq;': '⫌',
    'supsim;': '⫈',
    'supsub;': '⫔',
    'supsup;': '⫖',
    'swArr;': '⇙',
    'swarhk;': '⤦',
    'swarr;': '↙',
    'swarrow;': '↙',
    'swnwar;': '⤪',
    'szlig': 'ß',
    'szlig;': 'ß',
    'target;': '⌖',
    'tau;': 'τ',
    'tbrk;': '⎴',
    'tcaron;': 'ť',
    'tcedil;': 'ţ',
    'tcy;': 'т',
    'tdot;': '⃛',
    'telrec;': '⌕',
    'tfr;': '𝔱',
    'there4;': '∴',
    'therefore;': '∴',
    'theta;': 'θ',
    'thetasym;': 'ϑ',
    'thetav;': 'ϑ',
    'thickapprox;': '≈',
    'thicksim;': '∼',
    'thinsp;': '\u2009',
    'thkap;': '≈',
    'thksim;': '∼',
    'thorn': 'þ',
    'thorn;': 'þ',
    'tilde;': '˜',
    'times': '×',
    'times;': '×',
    'timesb;': '⊠',
    'timesbar;': '⨱',
    'timesd;': '⨰',
    'tint;': '∭',
    'toea;': '⤨',
    'top;': '⊤',
    'topbot;': '⌶',
    'topcir;': '⫱',
    'topf;': '𝕥',
    'topfork;': '⫚',
    'tosa;': '⤩',
    'tprime;': '‴',
    'trade;': '™',
    'triangle;': '▵',
    'triangledown;': '▿',
    'triangleleft;': '◃',
    'trianglelefteq;': '⊴',
    'triangleq;': '≜',
    'triangleright;': '▹',
    'trianglerighteq;': '⊵',
    'tridot;': '◬',
    'trie;': '≜',
    'triminus;': '⨺',
    'triplus;': '⨹',
    'trisb;': '⧍',
    'tritime;': '⨻',
    'trpezium;': '⏢',
    'tscr;': '𝓉',
    'tscy;': 'ц',
    'tshcy;': 'ћ',
    'tstrok;': 'ŧ',
    'twixt;': '≬',
    'twoheadleftarrow;': '↞',
    'twoheadrightarrow;': '↠',
    'uArr;': '⇑',
    'uHar;': '⥣',
    'uacute': 'ú',
    'uacute;': 'ú',
    'uarr;': '↑',
    'ubrcy;': 'ў',
    'ubreve;': 'ŭ',
    'ucirc': 'û',
    'ucirc;': 'û',
    'ucy;': 'у',
    'udarr;': '⇅',
    'udblac;': 'ű',
    'udhar;': '⥮',
    'ufisht;': '⥾',
    'ufr;': '𝔲',
    'ugrave': 'ù',
    'ugrave;': 'ù',
    'uharl;': '↿',
    'uharr;': '↾',
    'uhblk;': '▀',
    'ulcorn;': '⌜',
    'ulcorner;': '⌜',
    'ulcrop;': '⌏',
    'ultri;': '◸',
    'umacr;': 'ū',
    'uml': '¨',
    'uml;': '¨',
    'uogon;': 'ų',
    'uopf;': '𝕦',
    'uparrow;': '↑',
    'updownarrow;': '↕',
    'upharpoonleft;': '↿',
    'upharpoonright;': '↾',
    'uplus;': '⊎',
    'upsi;': 'υ',
    'upsih;': 'ϒ',
    'upsilon;': 'υ',
    'upuparrows;': '⇈',
    'urcorn;': '⌝',
    'urcorner;': '⌝',
    'urcrop;': '⌎',
    'uring;': 'ů',
    'urtri;': '◹',
    'uscr;': '𝓊',
    'utdot;': '⋰',
    'utilde;': 'ũ',
    'utri;': '▵',
    'utrif;': '▴',
    'uuarr;': '⇈',
    'uuml': 'ü',
    'uuml;': 'ü',
    'uwangle;': '⦧',
    'vArr;': '⇕',
    'vBar;': '⫨',
    'vBarv;': '⫩',
    'vDash;': '⊨',
    'vangrt;': '⦜',
    'varepsilon;': 'ϵ',
    'varkappa;': 'ϰ',
    'varnothing;': '∅',
    'varphi;': 'ϕ',
    'varpi;': 'ϖ',
    'varpropto;': '∝',
    'varr;': '↕',
    'varrho;': 'ϱ',
    'varsigma;': 'ς',
    'varsubsetneq;': '⊊︀',
    'varsubsetneqq;': '⫋︀',
    'varsupsetneq;': '⊋︀',
    'varsupsetneqq;': '⫌︀',
    'vartheta;': 'ϑ',
    'vartriangleleft;': '⊲',
    'vartriangleright;': '⊳',
    'vcy;': 'в',
    'vdash;': '⊢',
    'vee;': '∨',
    'veebar;': '⊻',
    'veeeq;': '≚',
    'vellip;': '⋮',
    'verbar;': '|',
    'vert;': '|',
    'vfr;': '𝔳',
    'vltri;': '⊲',
    'vnsub;': '⊂⃒',
    'vnsup;': '⊃⃒',
    'vopf;': '𝕧',
    'vprop;': '∝',
    'vrtri;': '⊳',
    'vscr;': '𝓋',
    'vsubnE;': '⫋︀',
    'vsubne;': '⊊︀',
    'vsupnE;': '⫌︀',
    'vsupne;': '⊋︀',
    'vzigzag;': '⦚',
    'wcirc;': 'ŵ',
    'wedbar;': '⩟',
    'wedge;': '∧',
    'wedgeq;': '≙',
    'weierp;': '℘',
    'wfr;': '𝔴',
    'wopf;': '𝕨',
    'wp;': '℘',
    'wr;': '≀',
    'wreath;': '≀',
    'wscr;': '𝓌',
    'xcap;': '⋂',
    'xcirc;': '◯',
    'xcup;': '⋃',
    'xdtri;': '▽',
    'xfr;': '𝔵',
    'xhArr;': '⟺',
    'xharr;': '⟷',
    'xi;': 'ξ',
    'xlArr;': '⟸',
    'xlarr;': '⟵',
    'xmap;': '⟼',
    'xnis;': '⋻',
    'xodot;': '⨀',
    'xopf;': '𝕩',
    'xoplus;': '⨁',
    'xotime;': '⨂',
    'xrArr;': '⟹',
    'xrarr;': '⟶',
    'xscr;': '𝓍',
    'xsqcup;': '⨆',
    'xuplus;': '⨄',
    'xutri;': '△',
    'xvee;': '⋁',
    'xwedge;': '⋀',
    'yacute': 'ý',
    'yacute;': 'ý',
    'yacy;': 'я',
    'ycirc;': 'ŷ',
    'ycy;': 'ы',
    'yen': '¥',
    'yen;': '¥',
    'yfr;': '𝔶',
    'yicy;': 'ї',
    'yopf;': '𝕪',
    'yscr;': '𝓎',
    'yucy;': 'ю',
    'yuml': 'ÿ',
    'yuml;': 'ÿ',
    'zacute;': 'ź',
    'zcaron;': 'ž',
    'zcy;': 'з',
    'zdot;': 'ż',
    'zeetrf;': 'ℨ',
    'zeta;': 'ζ',
    'zfr;': '𝔷',
    'zhcy;': 'ж',
    'zigrarr;': '⇝',
    'zopf;': '𝕫',
    'zscr;': '𝓏',
    'zwj;': '\u200d',
    'zwnj;': '\u200c',
}

# ---------------------------------------------------------------------------
# Parse error messages
# ---------------------------------------------------------------------------

E = {
    'XXX-undefined-error':
        'Undefined error (this sucks and should be fixed)',
    'adoption-agency-1.1':
        'End tag (%(name)s) violates step 1, paragraph 1 of the adoption agency algorithm.',
    'adoption-agency-1.2':
        'End tag (%(name)s) violates step 1, paragraph 2 of the adoption agency algorithm.',
    'adoption-agency-1.3':
        'End tag (%(name)s) violates step 1, paragraph 3 of the adoption agency algorithm.',
    'adoption-agency-4.4':
        'End tag (%(name)s) violates step 4, paragraph 4 of the adoption agency algorithm.',
    'attributes-in-end-tag':
        'End tag contains unexpected attributes.',
    'cant-convert-numeric-entity':
        "Numeric entity couldn't be converted to character (codepoint U+%(charAsInt)08x).",
    'char-in-head-noscript':
        'Unexpected non-space character. Expected inhead-noscript content',
    'deprecated-tag':
        "Unexpected start tag %(name)s. Don't use it!",
    'duplicate-attribute':
        'Dropped duplicate attribute on tag.',
    'end-tag-after-implied-root':
        'Unexpected end tag (%(name)s) after the (implied) root element.',
    'end-tag-too-early':
        'End tag (%(name)s) seen too early. Expected other end tag.',
    'end-tag-too-early-ignored':
        'End tag (%(name)s) seen too early. Ignored.',
    'end-tag-too-early-named':
        'Unexpected end tag (%(gotName)s). Expected end tag (%(expectedName)s).',
    'eof-in-attribute-name':
        'Unexpected end of file in attribute name.',
    'eof-in-attribute-value-double-quote':
        'Unexpected end of file in attribute value (").',
    'eof-in-attribute-value-no-quotes':
        'Unexpected end of file in attribute value.',
    'eof-in-attribute-value-single-quote':
        "Unexpected end of file in attribute value (').",
    'eof-in-comment':
        'Unexpected end of file in comment.',
    'eof-in-comment-double-dash':
        'Unexpected end of file in comment (--).',
    'eof-in-comment-end-bang-state':
        'Unexpected end of file in comment.',
    'eof-in-comment-end-dash':
        'Unexpected end of file in comment (-)',
    'eof-in-comment-end-space-state':
        'Unexpected end of file in comment.',
    'eof-in-doctype':
        'Unexpected end of file in DOCTYPE.',
    'eof-in-doctype-name':
        'Unexpected end of file in DOCTYPE name.',
    'eof-in-foreign-lands':
        'Unexpected end of file. Expected foreign content',
    'eof-in-frameset':
        'Unexpected end of file. Expected frameset content.',
    'eof-in-head-noscript':
        'Unexpected end of file. Expected inhead-noscript content',
    'eof-in-innerhtml':
        'XXX innerHTML EOF',
    'eof-in-script-in-script':
        'Unexpected end of file. Expected script content.',
    'eof-in-select':
        'Unexpected end of file. Expected select content.',
    'eof-in-table':
        'Unexpected end of file. Expected table content.',
    'eof-in-tag-name':
        'Unexpected end of file in the tag name.',
    'equals-in-unquoted-attribute-value':
        'Unexpected = in unquoted attribute',
    'expected-attribute-name-but-got-eof':
        'Unexpected end of file. Expected attribute name instead.',
    'expected-attribute-value-but-got-eof':
        'Unexpected end of file. Expected attribute value.',
    'expected-attribute-value-but-got-right-bracket':
        "Expected attribute value. Got '>' instead.",
    'expected-closing-tag-but-got-char':
        "Expected closing tag. Unexpected character '%(data)s' found.",
    'expected-closing-tag-but-got-eof':
        'Expected closing tag. Unexpected end of file.',
    'expected-closing-tag-but-got-right-bracket':
        "Expected closing tag. Got '>' instead. Ignoring '</>'.",
    'expected-dashes-or-doctype':
        "Expected '--' or 'DOCTYPE'. Not found.",
    'expected-doctype-but-got-chars':
        'Unexpected non-space characters. Expected DOCTYPE.',
    'expected-doctype-but-got-end-tag':
        'Unexpected end tag (%(name)s). Expected DOCTYPE.',
    'expected-doctype-but-got-eof':
        'Unexpected End of file. Expected DOCTYPE.',
    'expected-doctype-but-got-start-tag':
        'Unexpected start tag (%(name)s). Expected DOCTYPE.',
    'expected-doctype-name-but-got-eof':
        'Unexpected end of file. Expected DOCTYPE name.',
    'expected-doctype-name-but-got-right-bracket':
        'Unexpected > character. Expected DOCTYPE name.',
    'expected-end-of-tag-name-but-got-eof':
        'Unexpected end of file. Expected = or end of tag.',
    'expected-eof-but-got-char':
        'Unexpected non-space characters. Expected end of file.',
    'expected-eof-but-got-end-tag':
        'Unexpected end tag (%(name)s). Expected end of file.',
    'expected-eof-but-got-start-tag':
        'Unexpected start tag (%(name)s). Expected end of file.',
    'expected-named-closing-tag-but-got-eof':
        'Unexpected end of file. Expected end tag (%(name)s).',
    'expected-named-entity':
        'Named entity expected. Got none.',
    'expected-numeric-entity':
        'Numeric entity expected but none found.',
    'expected-numeric-entity-but-got-eof':
        'Numeric entity expected. Got end of file instead.',
    'expected-one-end-tag-but-got-another':
        'Unexpected end tag (%(gotName)s). Missing end tag (%(expectedName)s).',
    'expected-space-or-right-bracket-in-doctype':
        "Expected space or '>'. Got '%(data)s'",
    'expected-tag-name':
        'Expected tag name. Got something else instead',
    'expected-tag-name-but-got-question-mark':
        "Expected tag name. Got '?' instead. (HTML doesn't support processing instructions.)",
    'expected-tag-name-but-got-right-bracket':
        "Expected tag name. Got '>' instead.",
    'illegal-codepoint-for-numeric-entity':
        'Numeric entity represents an illegal codepoint: U+%(charAsInt)08x.',
    'illegal-windows-1252-entity':
        'Entity used with illegal number (windows-1252 reference).',
    'incorrect-comment':
        'Incorrect comment.',
    'incorrect-cr-newline-entity':
        'Incorrect CR newline entity, replaced with LF.',
    'incorrectly-placed-solidus':
        'Solidus (/) incorrectly placed in tag.',
    'invalid-character-after-attribute-name':
        'Unexpected character after attribute name.',
    'invalid-character-in-attribute-name':
        'Invalid character in attribute name',
    'invalid-codepoint':
        'Invalid codepoint in stream.',
    'missing-end-tag':
        'Missing end tag (%(name)s).',
    'missing-end-tags':
        'Missing end tags (%(name)s).',
    'named-entity-without-semicolon':
        "Named entity didn't end with ';'.",
    'need-space-after-doctype':
        "No space after literal string 'DOCTYPE'.",
    'no-end-tag':
        'This element (%(name)s) has no end tag.',
    'non-html-root':
        'html needs to be the first start tag.',
    'non-void-element-with-trailing-solidus':
        'Trailing solidus not allowed on element %(name)s',
    'null-character':
        'Null character in input stream, replaced with U+FFFD.',
    'numeric-entity-without-semicolon':
        "Numeric entity didn't end with ';'.",
    'self-closing-flag-on-end-tag':
        'End tag contains unexpected self-closing flag.',
    'two-heads-are-not-better-than-one':
        'Unexpected start tag head in existing head. Ignored.',
    'unexpected-EOF-after-solidus-in-tag':
        'Unexpected end of file in tag. Expected >',
    'unexpected-bang-after-double-dash-in-comment':
        'Unexpected ! after -- in comment',
    'unexpected-cell-end-tag':
        'Got table cell end tag (%(name)s) while required end tags are missing.',
    'unexpected-cell-in-table-body':
        'Unexpected table cell start tag (%(name)s) in the table body phase.',
    'unexpected-char-after-body':
        'Unexpected non-space characters in the after body phase.',
    'unexpected-char-after-frameset':
        'Unexpected non-space characters in the after frameset phase. Ignored.',
    'unexpected-char-implies-table-voodoo':
        'Unexpected non-space characters in table context caused voodoo mode.',
    'unexpected-char-in-comment':
        'Unexpected character in comment found.',
    'unexpected-char-in-doctype':
        'Unexpected character in DOCTYPE.',
    'unexpected-char-in-frameset':
        'Unexpected characters in the frameset phase. Characters ignored.',
    'unexpected-character-after-attribute-value':
        'Unexpected character after attribute value.',
    'unexpected-character-after-solidus-in-tag':
        'Unexpected character after / in tag. Expected >',
    'unexpected-character-in-unquoted-attribute-value':
        'Unexpected character in unquoted attribute',
    'unexpected-dash-after-double-dash-in-comment':
        "Unexpected '-' after '--' found in comment.",
    'unexpected-doctype':
        'Unexpected DOCTYPE. Ignored.',
    'unexpected-end-of-doctype':
        'Unexpected end of DOCTYPE.',
    'unexpected-end-tag':
        'Unexpected end tag (%(name)s). Ignored.',
    'unexpected-end-tag-after-body':
        'Unexpected end tag token (%(name)s) in the after body phase.',
    'unexpected-end-tag-after-body-innerhtml':
        'Unexpected end tag after body(innerHtml)',
    'unexpected-end-tag-after-frameset':
        'Unexpected end tag (%(name)s) in the after frameset phase. Ignored.',
    'unexpected-end-tag-before-html':
        'Unexpected end tag (%(name)s) before html.',
    'unexpected-end-tag-implies-table-voodoo':
        'Unexpected end tag (%(name)s) in table context caused voodoo mode.',
    'unexpected-end-tag-in-frameset':
        'Unexpected end tag token (%(name)s) in the frameset phase. Ignored.',
    'unexpected-end-tag-in-select':
        'Unexpected end tag (%(name)s) in the select phase. Ignored.',
    'unexpected-end-tag-in-table-body':
        'Unexpected end tag (%(name)s) in the table body phase. Ignored.',
    'unexpected-end-tag-in-table-row':
        'Unexpected end tag (%(name)s) in the table row phase. Ignored.',
    'unexpected-end-tag-treated-as':
        'Unexpected end tag (%(originalName)s). Treated as %(newName)s.',
    'unexpected-form-in-table':
        'Unexpected form in table context.',
    'unexpected-frameset-in-frameset-innerhtml':
        'Unexpected end tag token (frameset) in the frameset phase (innerHTML).',
    'unexpected-hidden-input-in-table':
        'Unexpected input with type hidden in table context.',
    'unexpected-html-element-in-foreign-content':
        'Element %(name)s not allowed in a non-html context',
    'unexpected-implied-end-tag-in-table':
        'Unexpected implied end tag (%(name)s) in the table phase.',
    'unexpected-implied-end-tag-in-table-body':
        'Unexpected implied end tag (%(name)s) in the table body phase.',
    'unexpected-implied-end-tag-in-table-row':
        'Unexpected implied end tag (%(name)s) in the table row phase.',
    'unexpected-inhead-noscript-tag':
        'Element %(name)s not allowed in a inhead-noscript context',
    'unexpected-input-in-select':
        'Unexpected input start tag in the select phase.',
    'unexpected-select-in-select':
        'Unexpected select start tag in the select phase treated as select end tag.',
    'unexpected-space-after-double-dash-in-comment':
        'Unexpected space after -- in comment',
    'unexpected-start-tag':
        'Unexpected start tag (%(name)s).',
    'unexpected-start-tag-after-body':
        'Unexpected start tag token (%(name)s) in the after body phase.',
    'unexpected-start-tag-after-frameset':
        'Unexpected start tag (%(name)s) in the after frameset phase. Ignored.',
    'unexpected-start-tag-ignored':
        'Unexpected start tag %(name)s. Ignored.',
    'unexpected-start-tag-implies-end-tag':
        'Unexpected start tag (%(startName)s) implies end tag (%(endName)s).',
    'unexpected-start-tag-implies-table-voodoo':
        'Unexpected start tag (%(name)s) in table context caused voodoo mode.',
    'unexpected-start-tag-in-frameset':
        'Unexpected start tag token (%(name)s) in the frameset phase. Ignored.',
    'unexpected-start-tag-in-select':
        'Unexpected start tag token (%(name)s in the select phase. Ignored.',
    'unexpected-start-tag-out-of-my-head':
        'Unexpected start tag (%(name)s) that can be in head. Moved.',
    'unexpected-start-tag-treated-as':
        'Unexpected start tag (%(originalName)s). Treated as %(newName)s.',
    'unexpected-table-element-end-tag-in-select-in-table':
        'Unexpected table element end tag (%(name)s) in the select in table phase.',
    'unexpected-table-element-start-tag-in-select-in-table':
        'Unexpected table element start tag (%(name)s) in the select in table phase.',
    'unknown-doctype':
        'Erroneous DOCTYPE.',
}
